"use client";
import { useState } from "react";

const projects = [
 
  {
    title: "AI-Powered Portfolio Assistant",
    description:
      "A personal portfolio enhanced with a real-time AI agent using Azure OpenAI, custom embeddings and RAG.",
    details: `I built this project to turn a standard developer portfolio into an interactive site with an AI assistant that can handle both casual questions and deeply contextual, skill based questions about my background, projects, and tech stack. Instead of a static page, the portfolio behaves like a product experience where visitors can explore my work and immediately get clear, accurate explanations of what I have built, how I built it, and why specific technical decisions were made.

The platform is built with Next.js, TypeScript, and Tailwind CSS, with modular UI components connected to serverless API routes that power the assistant. The chat experience is real time and streaming, so responses appear smoothly as tokens are generated rather than showing a delayed block of text. This makes the assistant feel like a first class feature of the portfolio and keeps the UX modern and fast.

To ensure accuracy and personalization, I implemented a Retrieval Augmented Generation pipeline. I structured resume and project metadata into JSON, chunked the content, generated embeddings using Azure OpenAI’s text embedding 3 large model, and stored them in a vector index for similarity search. At query time, the system retrieves the most relevant context and injects it into prompts before calling the LLM, enabling grounded answers that reference specific skills, tools, and achievements with reduced hallucination risk.`,
  },

 
  {
    title: "Agent Tina (Agentic AI Career Intelligence Platform)",
    description:
      "An actively developed multi-agent GenAI system using RAG and semantic search for ATS-aware resume–job matching.",
    details: `Agent Tina is an actively developed agentic AI system built to address a real and persistent problem in modern hiring: job matching is still driven by keyword filters, static ATS rules, and manual review. This approach regularly misses qualified candidates, provides little insight into why profiles fail ATS screening, and forces both recruiters and candidates to rely on trial-and-error. The result is inefficient hiring, poor transparency, and limited visibility into actual skill gaps or market alignment.

To solve this, I am building Agent Tina as a multi-agent, Retrieval-Augmented Generation (RAG) platform that continuously discovers job postings, understands resumes and job descriptions semantically, and produces explainable, ATS-aware matching insights. Instead of a single monolithic model, the system is designed around specialized AI agents that independently parse resumes, normalize job data from public sources, perform semantic matching, evaluate ATS-aligned fit signals, identify skill gaps, and remove duplicates across sources. Each insight generated by the system is grounded in retrieved evidence from vector search, ensuring reliability and reducing hallucination.

The project is being developed as a full-stack, production-oriented system rather than a demo. Current work focuses on building and hardening ingestion pipelines, improving retrieval quality and ranking logic, and adding validation and grounding guardrails to ensure consistent, explainable outputs. Agent Tina demonstrates my ability to design and implement agentic AI systems that combine reasoning, retrieval, and real-world constraints to solve complex problems in a scalable and maintainable way.`,
  },

  
  {
    title: "Integrated Healthcare Data Security System (Research Project)",
    description:
      "Smart security for sensitive healthcare data-compliant, encrypted, and resilient.",
    details: `During my Master’s program, I led a research project aimed at addressing the 
challenge of securing sensitive healthcare data while complying with HIPAA standards. 
I designed a secure database prototype with AES-256 and TLS 1.3 encryption, integrated 
role-based and attribute-based access control and applied graph-based algorithms to resolve 
complex user permission hierarchies. To further strengthen the system, I implemented real-time 
audit logging and anomaly detection using behavioral analytics. This project demonstrated how a 
carefully engineered system can safeguard patient data, prevent unauthorized access and detect potential
threats in real time, also proving the feasibility of combining strong cryptography with intelligent 
monitoring for healthcare security.`,
  },
];

export default function Projects() {
  const [active, setActive] = useState<number | null>(null);

  return (
    <div id="projects" className="w-full text-white py-20 lg:py-28">
      <div className="mx-auto max-w-6xl px-4 space-y-12">
        <h2 className="text-3xl lg:text-4xl font-bold text-center">Projects</h2>

        {/* Project cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
          {projects.map((proj, idx) => (
            <div
              key={idx}
              onClick={() => setActive(idx)}
              className="cursor-pointer p-6 rounded-xl border border-white/20 bg-white/5 hover:bg-white/10 transition"
            >
              <h3 className="text-xl font-semibold">{proj.title}</h3>
              <p className="mt-2 text-sm text-white/70">{proj.description}</p>
            </div>
          ))}
        </div>

        {/* Popup modal */}
        {active !== null && (
          <div
            className="fixed inset-0 z-50 flex items-center justify-center bg-black/70"
            onClick={() => setActive(null)} // click background closes modal
          >
            <div
              className="max-w-lg w-full bg-white text-black rounded-xl p-6 relative"
              onClick={(e) => e.stopPropagation()} // prevent closing when clicking inside
            >
              <button
                onClick={() => setActive(null)}
                className="absolute top-3 right-3 text-gray-500 hover:text-black"
              >
                ✕
              </button>

              <h3 className="text-2xl font-bold mb-4">
                {projects[active].title}
              </h3>

              
              <p className="leading-relaxed whitespace-pre-line">
                {projects[active].details}
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
